const divisions={
  math:['數學科','數字、幾何、邏輯、機率與最佳策略'],physics:['物理科','力、運動、聲、光、熱與電磁'],chemistry:['化學科','物質性質、反應、晶體與酸鹼'],biology:['生物科','生物構造、生長、行為與生態'],earth:['地球科學科','氣象、地質、天文、水與土壤'],applied1:['生活與應用科學科（一）','機械、能源、光電、物理、資訊工程應用'],applied2:['生活與應用科學科（二）','生物科技與食品科學'],applied3:['生活與應用科學科（三）','化學工程與環境科學']
};
const topics=[
  {id:'m1',d:'math',i:['遊戲','數字'],title:'障礙格與多人輪流規則如何改變井字棋策略',q:'加入不同障礙格或三人輪流規則後，先手優勢與必勝策略如何改變？',difficulty:'高',time:'4–6 週',cost:'幾乎免費',pros:'不是重做普通井字棋，而是建立新規則、分類局面並尋找可證明的策略。',cons:'已有多件井字棋科展作品；必須清楚說明新規則與前人研究的差異，最好用程式窮舉驗證。',iv:'障礙格位置、棋盤大小或玩家人數',dv:'可達局面數、勝敗和比例、是否存在必勝策略',cv:'連線規則、每位玩家可用棋子、勝負判定',safety:'低風險；若使用程式，保留演算法與測試紀錄。',why:'適合喜歡桌遊、邏輯分類與策略證明的學生。',develop:'先重現普通 3×3 結果作為基準，再只改一項規則；建立對稱局面分類，最後用程式窮舉和人工推理互相驗證。',works:[['第61屆國小數學科第一名〈探討多人玩的井字棋—Otrio是否有必勝方法〉','https://twsf.ntsec.gov.tw/activity/race-1/61/pdf/NPHSF2021-080403.pdf'],['第58屆國小數學科佳作〈棋盤上的奇蹟—奇「雞」連連〉','https://twsf.ntsec.gov.tw/activity/race-1/58/pdf/NPHSF2018-080402.pdf'],['第49屆國小數學科〈棋形怪狀〉','https://twsf.ntsec.gov.tw/activity/race-1/49/pdf/080404.pdf']]},
  {id:'m2',d:'math',i:['圖形','手作'],title:'不同摺法能把紙分成多少區域',q:'摺疊次數與紙面區域數之間有什麼規律？',difficulty:'中',time:'2–4 週',cost:'100 元內',pros:'可以實作、畫圖並尋找數列規律。',cons:'摺線重疊時容易計數錯誤。',iv:'摺疊次數與方向',dv:'展開後的區域數',cv:'紙張大小、摺疊規則',safety:'使用剪刀時由成人陪同。'},
  {id:'m3',d:'math',i:['植物','圖形'],title:'校園植物葉序與遮蔽率的數學模型',q:'不同植物的相鄰葉片角度，能否預測從上方觀察時的葉片重疊比例？',difficulty:'中高',time:'4–6 週',cost:'200–500 元',pros:'同時符合數學與植物興趣；核心是角度、比例、統計誤差與模型預測，不只是觀察植物。',cons:'真實葉片是立體且會彎曲，需限定植物種類、拍攝高度與量角方法。',iv:'模型中的葉片夾角，或不同植物種類的實測角度',dv:'投影重疊面積比例、實測值與模型預測的誤差',cv:'葉片數、模型葉片大小、拍攝高度、影像比例尺',safety:'只拍攝或量測校園常見植物，不採集稀有植物；戶外觀察由教師陪同。',why:'「植物」提供真實資料，「數學科」負責建立角度模型、計算遮蔽率並分析預測誤差。',develop:'不要只驗證是否符合費氏數列。先比較 3–5 種校園植物，再用紙片或電腦模型測試 90°、120°、137.5°等角度；最後檢驗哪種模型最能預測真實遮蔽率，並討論不符合黃金角的例外。',works:[['第48屆國小組自然科第三名〈向日葵的生長密碼〉','https://twsf.ntsec.gov.tw/activity/race-1/48/pdf/081544.pdf'],['第49屆高中組數學科第三名〈向日葵裡的黃金項鏈〉','https://twsf.ntsec.gov.tw/activity/race-1/49/pdf/040418.pdf'],['第49屆國中組數學科〈費伯那西？盧卡斯？向日葵到底愛誰？〉','https://twsf.ntsec.gov.tw/activity/race-1/49/pdf/030409.pdf']]},
  {id:'p1',d:'physics',i:['飛行','玩具'],title:'紙飛機機翼寬度與飛行距離',q:'只改變機翼寬度時，紙飛機的平均飛行距離如何改變？',difficulty:'低',time:'2–3 週',cost:'100 元內',pros:'現象直觀、材料便宜、容易重複。',cons:'投擲力量與風會造成很大誤差。',iv:'機翼寬度',dv:'飛行距離與滯空時間',cv:'紙張、重量、投擲器、場地',safety:'在空曠室內進行，不朝人投擲。'},
  {id:'p2',d:'physics',i:['聲音','音樂'],title:'生活材料的隔音效果',q:'相同厚度下，哪些常見材料最能降低聲音強度？',difficulty:'中',time:'2–3 週',cost:'300–600 元',pros:'與生活相關，可用手機分貝計初步比較。',cons:'手機不是專業聲級計，環境噪音需控制。',iv:'隔音材料',dv:'量得的相對分貝變化',cv:'聲源、距離、厚度、房間',safety:'避免長時間播放大音量。'},
  {id:'c1',d:'chemistry',i:['結晶','食物'],title:'溫度與糖晶體生長',q:'不同冷卻條件會如何影響糖晶體的大小與數量？',difficulty:'中',time:'3–4 週',cost:'200–400 元',pros:'變化可拍照，能量測晶體大小。',cons:'蒸發量與雜質會影響結果。',iv:'冷卻或保存溫度',dv:'晶體大小、數量、質量',cv:'糖水濃度、容器、時間',safety:'熱糖液會燙傷，必須由成人協助加熱。'},
  {id:'c2',d:'chemistry',i:['清潔','生活'],title:'不同酸性液體的除垢效果',q:'相同酸鹼值或濃度下，不同食用酸對水垢的去除效果如何？',difficulty:'中',time:'2–3 週',cost:'200–400 元',pros:'生活性高，可用質量變化比較。',cons:'必須先統一水垢樣本大小。',iv:'食用酸種類',dv:'樣本質量減少量',cv:'液體體積、時間、溫度',safety:'只使用食用級材料，戴護目鏡，不混合清潔劑。'},
  {id:'b1',d:'biology',i:['植物','光線'],title:'光的方向與豆苗彎曲',q:'不同方向的光會讓豆苗彎曲多少？',difficulty:'低',time:'3–4 週',cost:'200–400 元',pros:'現象明顯，可每日拍照與量角度。',cons:'種子個體差異大，需要足夠樣本。',iv:'光源方向',dv:'彎曲角度與高度',cv:'種子、土壤、水量、溫度、光照時間',safety:'低風險；實驗後妥善處理植物。'},
  {id:'b2',d:'biology',i:['昆蟲','食物'],title:'螞蟻的覓食選擇',q:'在不傷害螞蟻的條件下，不同糖濃度是否影響螞蟻到訪次數？',difficulty:'中',time:'3–5 週',cost:'100 元內',pros:'可觀察真實行為與重複試驗。',cons:'天氣、蟻群位置和氣味都會干擾。',iv:'糖水濃度',dv:'固定時間內到訪次數',cv:'位置、容器、時間、液體量',safety:'不捕捉、不餵有害物；避免在室內引入蟻群。'},
  {id:'e1',d:'earth',i:['土壤','環境'],title:'不同土壤的抗沖刷能力',q:'相同坡度與水量下，哪種土壤流失得最少？',difficulty:'中',time:'2–4 週',cost:'300–600 元',pros:'可模擬降雨並量測流失質量。',cons:'土壤含水量和顆粒大小不易完全一致。',iv:'土壤種類',dv:'流失土壤質量、出水混濁度',cv:'坡度、水量、面積、初始含水量',safety:'地面防滑；土壤不入口，操作後洗手。'},
  {id:'e2',d:'earth',i:['天氣','校園'],title:'校園不同地面的微氣候',q:'草地、泥土與水泥地表的溫度變化有何差異？',difficulty:'低',time:'2–3 週',cost:'200–500 元',pros:'貼近校園生活，能累積時間序列資料。',cons:'陰影、風和測量時刻會造成干擾。',iv:'地表種類',dv:'表面或近地氣溫',cv:'測量時間、高度、儀器、天氣條件',safety:'避免中午曝曬，戶外測量需有同伴。'},
  {id:'a11',d:'applied1',i:['植物','工程'],title:'節水自動澆水裝置',q:'哪種土壤濕度門檻能在維持植物生長時減少用水？',difficulty:'高',time:'5–8 週',cost:'800–1500 元',pros:'結合感測器、程式與植物生長。',cons:'感測器校正與故障排除需要時間。',iv:'啟動澆水的濕度門檻',dv:'用水量與植物生長',cv:'植物、盆器、土壤、光照',safety:'只使用低電壓設備，水與電路分離，教師監督。'},
  {id:'a12',d:'applied1',i:['能源','食物'],title:'太陽能烘乾箱的結構改良',q:'不同內壁顏色或通風孔面積如何影響箱內升溫與乾燥速度？',difficulty:'高',time:'4–6 週',cost:'500–1000 元',pros:'能反覆改良裝置並評估能源應用。',cons:'天氣變化大，需要多日重複測量。',iv:'內壁顏色或通風孔面積',dv:'溫度與樣品質量下降速度',cv:'箱體、樣品、日照時段',safety:'避免密閉過熱與食用實驗後樣品。'},
  {id:'a21',d:'applied2',i:['食物','發酵'],title:'優格發酵溫度與凝固狀態',q:'在安全控溫下，不同發酵溫度如何影響優格的酸度與凝固時間？',difficulty:'高',time:'3–5 週',cost:'500–900 元',pros:'能量測時間、酸鹼值與質地。',cons:'食品衛生與穩定控溫要求高。',iv:'發酵溫度',dv:'pH、凝固時間、流動性',cv:'牛奶、菌種、容器、份量',safety:'需教師或成人監督；實驗樣品不得食用。'},
  {id:'a22',d:'applied2',i:['食物','保存'],title:'麵包包裝方式與水分散失',q:'不同包裝方式如何影響麵包在短期內的質量與硬度變化？',difficulty:'中',time:'2–3 週',cost:'300–600 元',pros:'材料易得，能以質量與固定壓力變形量比較。',cons:'不能以長黴速度作為主要實驗，避免培養未知微生物。',iv:'包裝方式',dv:'質量變化與壓縮變形',cv:'同批麵包、大小、溫度、時間',safety:'不開啟或嗅聞發霉樣品；密封後由成人丟棄。'},
  {id:'a31',d:'applied3',i:['水','環境'],title:'簡易濾材對混濁水的改善',q:'砂、礫石與活性碳的排列方式如何影響模擬混濁水的清澈度？',difficulty:'中',time:'3–4 週',cost:'400–800 元',pros:'工程結構可改良，結果容易比較。',cons:'變清澈不代表可以飲用，需明確說明限制。',iv:'濾材種類與排列',dv:'透光度、過濾時間',cv:'模擬水、濾材量、容器',safety:'只用泥土製作模擬污水；過濾水絕對不可飲用。'},
  {id:'a32',d:'applied3',i:['回收','材料'],title:'再生紙配方與強度',q:'廢紙紙漿中不同天然纖維比例如何影響再生紙的承重能力？',difficulty:'中',time:'3–5 週',cost:'300–700 元',pros:'結合資源再利用與材料測試。',cons:'紙張厚度與乾燥程度要控制。',iv:'添加纖維比例',dv:'厚度、最大承重、吸水性',cv:'紙漿量、紙張面積、乾燥方式',safety:'使用果汁機與剪刀時需成人陪同。'}
];
const interestOptions=['植物','動物／昆蟲','食物','水／環境','玩具／工程','聲音／音樂','天氣／星空','數字／圖形'];
const storeKey='scienceFairCoachV1';
let state=load();
const app=document.querySelector('#app');
function safeUrl(value){try{const url=new URL(value);return url.protocol==='https:'?url.href:'#'}catch{return '#'}}
function load(){try{return {...{screen:'home',division:'',grade:'',weeks:'',budget:'',interests:[],observation:'',topicId:''},...JSON.parse(localStorage.getItem(storeKey)||'{}')}}catch{return {screen:'home',division:'',interests:[]}}}
function save(){localStorage.setItem(storeKey,JSON.stringify(state))}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function progress(n){return `<div class="progress" aria-label="目前第 ${n} 步">${[1,2,3,4].map(x=>`<span class="${x<=n?'on':''}"></span>`).join('')}</div>`}
function render(){const views={home,division,profile,recommend,plan,teacher};app.innerHTML=(views[state.screen]||home)();app.focus();window.scrollTo({top:0,behavior:'smooth'})}
function home(){return `<section class="panel hero"><div class="mascot">💡</div><div class="eyebrow">把好奇心變成真正的實驗</div><h1>今天想研究<br>什麼呢？</h1><p>完成三個簡單步驟，找到安全、有趣，而且真的做得完的科展題目。</p><div class="actions"><button class="primary" data-go="division">開始找題目</button>${state.topicId?'<button class="secondary" data-go="plan">繼續上次計畫</button>':''}</div></section>`}
function division(){return `<section class="panel">${progress(1)}<div class="eyebrow">第 1 步｜可以隨時更換</div><h2>想參加哪一個科別？</h2><p>不確定也沒關係，先選最感興趣的方向。</p><div class="options">${Object.entries(divisions).map(([k,v])=>`<button class="option ${state.division===k?'selected':''}" data-division="${k}"><strong>${v[0]}</strong><small>${v[1]}</small></button>`).join('')}</div><div class="actions"><button class="secondary" data-go="home">返回</button><button class="primary" data-next="profile" ${state.division?'':'disabled'}>下一步</button></div></section>`}
function profile(){return `<section class="panel">${progress(2)}<div class="eyebrow">第 2 步｜可以返回修改</div><h2>告訴我你的條件</h2><div class="form-grid"><div class="field"><label for="grade">年級</label><select id="grade"><option value="">請選擇</option>${[4,5,6].map(n=>`<option ${String(state.grade)===String(n)?'selected':''}>${n}</option>`).join('')}</select></div><div class="field"><label for="weeks">還有幾週？</label><input id="weeks" type="number" min="1" max="52" value="${esc(state.weeks)}" placeholder="例如：8"></div><div class="field"><label for="budget">材料預算</label><select id="budget"><option value="">請選擇</option>${['500 元內','1000 元內','1500 元以上'].map(x=>`<option ${state.budget===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field wide"><label>你喜歡哪些事物？可複選</label><div class="chips">${interestOptions.map(x=>`<button class="chip ${state.interests.includes(x)?'selected':''}" data-interest="${x}" type="button">${x}</button>`).join('')}</div></div><div class="field wide"><label for="observation">最近有沒有讓你好奇的現象？</label><textarea id="observation" placeholder="例如：窗邊的豆苗好像都朝同一邊長……">${esc(state.observation)}</textarea></div></div><div class="actions"><button class="secondary" data-go="division">更換科別</button><button class="primary" data-profile>看看推薦題目</button></div></section>`}
function ranked(){const list=topics.filter(t=>t.d===state.division);return list.sort((a,b)=>score(b)-score(a)).slice(0,3)}
function score(t){const joined=(t.i||[]).join('');return state.interests.reduce((n,x)=>n+(joined.includes(x.split('／')[0])?2:0),0)+Math.random()*.01}
function works(t){if(!t.works?.length)return '';return `<details class="works"><summary>查看科教館歷屆相關作品（${t.works.length}）</summary><ul>${t.works.map(([name,url])=>`<li><a href="${url}" target="_blank" rel="noopener">${name}</a></li>`).join('')}</ul><p>歷屆作品用來了解前人做到哪裡，不可直接複製題目、方法或文字。</p></details>`}
function topicCard(t){return `<article class="topic ${state.topicId===t.id?'selected':''}"><div class="topic-head"><div><span class="tag">${divisions[t.d][0]}</span><h3>${t.title}</h3></div><button class="secondary" data-topic="${t.id}">${state.topicId===t.id?'已選擇':'選這一題'}</button></div>${t.why?`<p class="match"><strong>為什麼符合：</strong>${t.why}</p>`:''}<p><strong>研究問題：</strong>${t.q}</p><div class="facts"><div class="fact"><small>難度</small>${t.difficulty}</div><div class="fact"><small>時間</small>${t.time}</div><div class="fact"><small>預估材料費</small>${t.cost}</div></div><p><strong>優點：</strong>${t.pros}</p><p><strong>可能困難：</strong>${t.cons}</p>${t.develop?`<div class="development"><strong>創新發展建議：</strong>${t.develop}</div>`:''}${works(t)}<div class="notice"><strong>安全提醒：</strong>${t.safety}</div></article>`}
function alternateAdvice(){const hasPlant=state.interests.includes('植物');if(state.division==='math'&&hasPlant)return '<div class="advisor"><strong>科別判斷：</strong>若研究重點是角度、數列、遮蔽比例與模型誤差，可留在數學科；若重點是光照造成的生長差異，生物科更合適；若要製作自動栽培裝置，則考慮生活與應用科學科（一）。</div>';const map={'動物／昆蟲':'biology','食物':'applied2','水／環境':'applied3','玩具／工程':'applied1','聲音／音樂':'physics','天氣／星空':'earth','數字／圖形':'math'};const alt=state.interests.map(x=>map[x]).find(x=>x&&x!==state.division);return alt?`<div class="advisor"><strong>也可以考慮：</strong>${divisions[alt][0]}。如果你更重視「${state.interests.find(x=>map[x]===alt)}」本身，而不是目前科別的方法，這個科別可能更合適。</div>`:''}
function aiPanel(){if(!window.ScienceFairBackend?.enabled())return '<div class="notice"><strong>動態題目尚未連線：</strong>目前顯示經人工整理的安全題庫。</div>';if(!state.aiResult)return '<div class="ai-box"><h3>🌏 搜尋近期議題與科教館作品</h3><p>系統會再問幾個問題，並搜尋近兩年議題與可核對的科教館資料。每位學生每日最多5次。</p><button class="primary" data-ai-start>開始動態找題</button><p id="ai-status"></p></div>';if(state.aiResult.stage==='questions')return `<div class="ai-box"><h3>先回答幾個問題</h3><div class="portal-form">${state.aiResult.questions.map((q,i)=>`<label>${esc(q)}<textarea data-ai-answer="${i}"></textarea></label>`).join('')}<button class="primary" data-ai-submit>送出並搜尋題目</button></div><p id="ai-status"></p></div>`;return `<div class="ai-box"><h3>近期議題動態推薦</h3><div class="topics">${state.aiResult.topics.map((t,i)=>`<article class="topic ${state.topicId===`ai:${i}`?'selected':''}"><div class="topic-head"><div><span class="tag">${esc(t.division)}</span><h3>${esc(t.title)}</h3></div><button class="secondary" data-ai-topic="${i}">${state.topicId===`ai:${i}`?'已選擇':'選這一題'}</button></div><p><strong>為什麼符合：</strong>${esc(t.fit)}</p><p><strong>近期議題：</strong>${esc(t.current_issue)}</p><p><strong>研究問題：</strong>${esc(t.research_question)}</p><div class="development"><strong>創新方向：</strong>${esc(t.novelty)}</div><p><strong>變因：</strong>${esc(t.variables)}</p><p><strong>可行性：</strong>${esc(t.feasibility)}</p><div class="notice"><strong>安全：</strong>${esc(t.safety)}</div>${t.prior_works?.length?`<details class="works"><summary>科教館相關作品</summary><ul>${t.prior_works.map(w=>`<li><a href="${esc(safeUrl(w.url))}" target="_blank" rel="noopener">${esc(w.title)}</a>－${esc(w.relationship)}</li>`).join('')}</ul></details>`:'<p>尚未找到可核對的科教館相關作品。</p>'}</article>`).join('')}</div>${state.aiResult.sources?.length?`<details class="works"><summary>本次近期議題來源</summary><ul>${state.aiResult.sources.map(s=>`<li><a href="${esc(safeUrl(s.url))}" target="_blank" rel="noopener">${esc(s.title)}</a>｜${esc(s.published_date)}｜${esc(s.kind)}</li>`).join('')}</ul></details>`:''}</div>`}
function recommend(){const list=ranked();return `<section class="panel">${progress(3)}<div class="eyebrow">第 3 步｜可以換題或返回修改</div><h2>同時符合科別與興趣的題目</h2><p>推薦會先符合所選科別，再用興趣與生活觀察排序；也會指出可能更適合的科別。</p>${aiPanel()}${alternateAdvice()}<h3>經人工整理的備援題目</h3><div class="topics">${list.map(topicCard).join('')}</div><div class="actions"><button class="secondary" data-go="profile">修改興趣與條件</button><button class="secondary" data-reroll>重新排序</button><button class="primary" data-next="plan" ${state.topicId?'':'disabled'}>建立研究摘要</button></div></section>`}
function selected(){if(String(state.topicId).startsWith('ai:')){const i=Number(state.topicId.split(':')[1]),x=state.aiResult?.topics?.[i];if(x)return {id:state.topicId,d:state.division,title:x.title,q:x.research_question,difficulty:'由教師評估',time:x.feasibility,cost:'依器材確認',pros:x.fit,cons:x.novelty,iv:x.variables,dv:'見變因說明',cv:'見變因說明',safety:x.safety,works:x.prior_works}}return topics.find(t=>t.id===state.topicId)}
function plan(){const t=selected();if(!t)return empty('還沒有選擇題目','recommend');return `<section class="panel">${progress(4)}<div class="eyebrow">研究摘要</div><h2>${t.title}</h2><div class="summary"><section class="wide"><h3>研究問題</h3><p>${t.q}</p></section><section><h3>變因設計</h3><p><strong>操縱變因：</strong>${t.iv}</p><p><strong>應變變因：</strong>${t.dv}</p><p><strong>控制變因：</strong>${t.cv}</p></section><section><h3>可行性</h3><p>難度：${t.difficulty}<br>時間：${t.time}<br>材料費：${t.cost}</p></section><section><h3>安全檢查</h3><p>${t.safety}</p></section><section><h3>下一步</h3><ul><li>用自己的話改寫研究問題</li><li>請老師確認安全與器材</li><li>查找至少三項相關作品或文獻</li><li>先做一次小規模預備實驗</li></ul></section></div><p class="saved">✓ 已自動儲存在這台裝置</p><div class="actions"><button class="secondary" data-go="recommend">更換題目</button><button class="primary" data-action="teacher">開啟教師檢視</button></div></section>`}
function teacher(){const t=selected();if(!t)return empty('學生尚未完成選題','home');return `<section class="panel"><div class="eyebrow">教師／家長檢視</div><h2>${t.title}</h2><p>學生條件：${esc(state.grade||'未填')} 年級｜${esc(state.weeks||'未填')} 週｜${esc(state.budget||'未填')}</p><div class="summary"><section><h3>科別</h3><p>${divisions[t.d][0]}</p></section><section><h3>學生興趣</h3><p>${esc(state.interests.join('、')||'未填')}</p></section><section class="wide"><h3>生活觀察</h3><p>${esc(state.observation||'未填')}</p></section><section><h3>題目優點</h3><p>${t.pros}</p></section><section><h3>待處理問題</h3><p>${t.cons}</p></section><section class="wide"><h3>教師確認清單</h3><ul><li>題目是否由學生理解並願意研究？</li><li>變因是否清楚且能量測？</li><li>樣本數與重複次數是否足夠？</li><li>是否符合安全、倫理與地方科展規定？</li><li>是否查過歷屆作品，避免高度重複？</li></ul></section></div><div class="actions"><button class="secondary" data-go="plan">返回學生摘要</button><button class="primary" onclick="window.print()">列印／另存 PDF</button></div></section>`}
function empty(msg,go){return `<section class="panel empty"><div class="mascot">🧭</div><h2>${msg}</h2><div class="actions"><button class="primary" data-go="${go}">前往選題</button></div></section>`}
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-go]');if(!b)return;if(b.dataset.go){state.screen=b.dataset.go;save();render()}if(b.dataset.action==='home'){state.screen='home';render()}if(b.dataset.action==='teacher'){state.screen='teacher';render()}if(b.dataset.action==='reset'&&confirm('要清除目前的選題紀錄並重新開始嗎？')){localStorage.removeItem(storeKey);state=load();render()}if(b.dataset.division){state.division=b.dataset.division;state.topicId='';save();render()}if(b.dataset.interest){state.interests=state.interests.includes(b.dataset.interest)?state.interests.filter(x=>x!==b.dataset.interest):[...state.interests,b.dataset.interest];save();render()}if(b.dataset.profile!==undefined){state.grade=document.querySelector('#grade').value;state.weeks=document.querySelector('#weeks').value;state.budget=document.querySelector('#budget').value;state.observation=document.querySelector('#observation').value.trim();state.screen='recommend';save();render()}if(b.dataset.topic){state.topicId=b.dataset.topic;save();render()}if(b.dataset.next){state.screen=b.dataset.next;save();render()}if(b.dataset.reroll!==undefined)render()});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.division)window.ScienceFairBackend?.track('division_selected',{division:b.dataset.division},{profile:state});if(b.dataset.interest)window.ScienceFairBackend?.track('interest_selected',{interest:b.dataset.interest,selected:state.interests.includes(b.dataset.interest)},{profile:state});if(b.dataset.profile!==undefined){window.ScienceFairBackend?.track('profile_updated',{grade:state.grade,weeks:state.weeks,budget:state.budget},{profile:state});if(state.observation)window.ScienceFairBackend?.track('observation_entered',{text:state.observation},{profile:state});window.ScienceFairBackend?.track('topics_recommended',{topic_ids:ranked().map(t=>t.id)},{});}if(b.dataset.topic){const t=selected();window.ScienceFairBackend?.track('topic_selected',{id:t?.id,title:t?.title},{profile:state,selectedTopic:t});}if(b.dataset.next==='plan'){const t=selected();window.ScienceFairBackend?.track('plan_created',{id:t?.id,title:t?.title},{profile:state,selectedTopic:t});}});
document.addEventListener('click',e=>{const link=e.target.closest('.works a');if(link)window.ScienceFairBackend?.track('source_opened',{title:link.textContent,url:link.href})});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const status=()=>document.querySelector('#ai-status');if(b.dataset.aiStart!==undefined){b.disabled=true;if(status())status().textContent='正在判斷還需要問什麼…';try{state.aiResult=await window.ScienceFairBackend.recommend(state,state.aiAnswers||[]);save();render()}catch(error){b.disabled=false;if(status())status().textContent=error.message}}if(b.dataset.aiSubmit!==undefined){const answers=[...document.querySelectorAll('[data-ai-answer]')].map((el,i)=>({question:state.aiResult.questions[i],answer:el.value.trim()}));if(answers.some(x=>!x.answer)){if(status())status().textContent='請先回答每一題。';return}b.disabled=true;if(status())status().textContent='正在搜尋近期議題與歷屆作品…';try{state.aiAnswers=[...(state.aiAnswers||[]),...answers];state.aiResult=await window.ScienceFairBackend.recommend(state,state.aiAnswers);save();render()}catch(error){b.disabled=false;if(status())status().textContent=error.message}}if(b.dataset.aiTopic!==undefined){state.topicId=`ai:${b.dataset.aiTopic}`;const t=selected();save();window.ScienceFairBackend.track('topic_selected',{id:t.id,title:t.title,mode:'dynamic'},{profile:state,selectedTopic:t});render()}});
render();
if(window.ScienceFairBackend?.enabled())window.ScienceFairBackend.get().then(data=>{if(data?.student?.profile){state={...state,...data.student.profile};if(data.student.selected_topic?.id)state.topicId=data.student.selected_topic.id;save();render()}}).catch(console.warn);
