import {JSDOM} from 'jsdom';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync('index.html','utf8').replace('<script src="app.js"></script>','');
const dom=new JSDOM(html,{url:'https://example.test/',runScripts:'dangerously'});
dom.window.confirm=()=>true;
dom.window.scrollTo=()=>{};
dom.window.eval(fs.readFileSync('app.js','utf8'));
const {document}=dom.window;
const click=selector=>{const el=document.querySelector(selector);assert.ok(el,`找不到 ${selector}`);el.click()};
click('[data-go="division"]');
assert.match(document.querySelector('#app').textContent,/想參加哪一個科別/);
click('[data-division="biology"]');
click('[data-next="profile"]');
document.querySelector('#grade').value='5';
document.querySelector('#weeks').value='8';
document.querySelector('#budget').value='10,000 元';
document.querySelector('#observation').value='我發現窗邊豆苗朝著陽光彎曲';
click('[data-interest="植物"]');
click('[data-profile]');
assert.match(document.querySelector('#app').textContent,/第 1 輪/);
assert.match(document.querySelector('#app').textContent,/豆苗朝著陽光彎曲/);
assert.doesNotMatch(document.querySelector('#app').textContent,/經人工整理的備援題目/);
document.querySelector('#guide-answer').value='我喜歡每天觀察窗邊豆苗朝著陽光彎曲的樣子';
click('[data-guide-submit]');await new Promise(resolve=>setTimeout(resolve,0));
document.querySelector('#guide-answer').value='我想知道光從不同方向照過來是不是會讓彎曲角度不同';
click('[data-guide-submit]');await new Promise(resolve=>setTimeout(resolve,0));
assert.match(document.querySelector('#app').textContent,/查看人工整理的備援題目/);
click('[data-go="profile"]');
assert.equal(document.querySelector('#grade').value,'5');
assert.equal(document.querySelector('#weeks').value,'8');
assert.equal(document.querySelector('#budget').value,'10,000 元');
assert.match(document.querySelector('#app').textContent,/上一步：選擇科別/);
click('[data-profile]');
assert.match(document.querySelector('#app').textContent,/我喜歡每天觀察窗邊豆苗/);
assert.doesNotMatch(document.querySelector('#app').textContent,/經人工整理的備援題目/);
click('[data-guide-finish]');
assert.match(document.querySelector('#app').textContent,/經人工整理的備援題目/);
assert.doesNotMatch(document.querySelector('#app').textContent,/動態找題|動態搜尋|搜尋近期議題/);
click('[data-topic="b1"]');
assert.match(document.querySelector('#app').textContent,/已鎖定這個研究方向/);
click('[data-next="plan"]');
assert.match(document.querySelector('#app').textContent,/光的方向與豆苗彎曲/);
assert.match(document.querySelector('#app').textContent,/繼續討論或上傳實驗紀錄/);
assert.match(document.querySelector('#app').textContent,/查看備援題目／更換題目/);
click('[data-go="experiment"]');
assert.match(document.querySelector('#app').textContent,/繼續和教練討論/);
document.querySelector('#discussion-question').value='光源角度應該分成幾組比較好？';
click('[data-discussion-submit]');await new Promise(resolve=>setTimeout(resolve,0));
assert.match(document.querySelector('#app').textContent,/學生問題：光源角度應該分成幾組/);
document.querySelector('#record-method').value='設三組不同光源方向，每組重複測量五次';
document.querySelector('#record-result').value='平均彎曲角度分別是 10、25、40 度';
click('[data-record-submit]');await new Promise(resolve=>setTimeout(resolve,0));
assert.match(document.querySelector('#app').textContent,/教練回覆/);
click('[data-go="plan"]');
assert.doesNotMatch(document.querySelector('#app').textContent,/開啟教師檢視/);
assert.equal(document.querySelector('[data-action="teacher"]'),null);
assert.equal(JSON.parse(dom.window.localStorage.getItem('scienceFairCoachV1')).topicId,'b1');
assert.equal(JSON.parse(dom.window.localStorage.getItem('scienceFairCoachV1')).budget,'10,000 元');
assert.match(document.querySelector('#current-user').textContent,/未登入/);
click('[data-go="reflection"]');
assert.ok(document.querySelector('#reflection-date').value);
document.querySelector('[name="learned"]').value='我學會了每次實驗只能改變一個條件';
document.querySelector('[name="difficult"]').value='控制每一盆植物的水量完全相同很困難';
document.querySelector('#reflection-form').requestSubmit();await new Promise(resolve=>setTimeout(resolve,0));
assert.match(document.querySelector('#app').textContent,/每次實驗只能改變一個條件/);
assert.match(document.querySelector('#app').textContent,/控制每一盆植物的水量/);
click('[data-action="reset"]');
click('[data-go="division"]');
click('[data-division="math"]');
click('[data-next="profile"]');
click('[data-interest="植物"]');
click('[data-profile]');
document.querySelector('#guide-answer').value='我喜歡觀察校園裡不同植物葉子的排列方式';
click('[data-guide-submit]');await new Promise(resolve=>setTimeout(resolve,0));
document.querySelector('#guide-answer').value='我想知道葉片角度是否會影響互相遮住的面積';
click('[data-guide-submit]');await new Promise(resolve=>setTimeout(resolve,0));
click('[data-guide-finish]');
const recommendation=document.querySelector('#app').textContent;
assert.match(recommendation,/校園植物葉序與遮蔽率的數學模型/);
assert.match(recommendation,/生物科更合適/);
assert.match(recommendation,/向日葵的生長密碼/);
console.log('✓ 選題流程、學生端角色隔離、本機儲存、科別＋興趣交集與歷屆作品皆通過');

const portalHtml=fs.readFileSync('portal.html','utf8').replace(/<script[^>]*><\/script>/g,'');
const portalDom=new JSDOM(portalHtml,{url:'https://example.test/portal.html',runScripts:'dangerously'});
portalDom.window.eval(fs.readFileSync('config.js','utf8'));
portalDom.window.fetch=async()=>({ok:true,json:async()=>({teacherGoogleLogin:false})});
portalDom.window.supabase={createClient:()=>({auth:{
  getSession:async()=>({data:{session:null}}),
  onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})
}})};
portalDom.window.eval(fs.readFileSync('portal.js','utf8'));
await new Promise(resolve=>setTimeout(resolve,0));
assert.doesNotMatch(portalDom.window.document.querySelector('#portal').textContent,/後端尚未連線/);
assert.equal(portalDom.window.document.querySelector('#google'),null);
assert.equal(portalDom.window.document.querySelector('#teacher-email').disabled,false);
assert.match(portalDom.window.document.querySelector('#current-user').textContent,/未登入/);

const migration=fs.readFileSync('supabase/migrations/202607180001_initial.sql','utf8');
for(const required of ['enable row level security','365 days','395 days','purge_expired_students','pg_cron','teachers view thought histories'])assert.ok(migration.includes(required),`migration缺少 ${required}`);
const studentApi=fs.readFileSync('supabase/functions/student-api/index.ts','utf8');
assert.match(studentApi,/PBKDF2/);assert.match(studentApi,/嘗試次數過多/);
assert.match(studentApi,/action==='list_students'/);assert.match(studentApi,/select\('student_code'\)/);
assert.match(studentApi,/reflection_added/);
const portalJs=fs.readFileSync('portal.js','utf8');
assert.match(portalJs,/使用 Email 與密碼登入/);assert.doesNotMatch(portalJs,/舊學生代號/);
assert.match(portalJs,/發現問題/);assert.match(portalJs,/拆解問題/);assert.match(portalJs,/用證據判斷/);assert.match(portalJs,/反思與負責/);
assert.match(portalJs,/學生的原始想法/);assert.match(portalJs,/教師或系統提問/);assert.match(portalJs,/學生提供的證據/);assert.match(portalJs,/想法如何改變/);assert.match(portalJs,/目前仍需追問之處/);assert.match(portalJs,/證據充足/);
assert.match(portalJs,/學生心得歷程/);
assert.match(portalJs,/帳號管理/);assert.match(portalJs,/不可查看（已加密保存）/);assert.match(portalJs,/teacher-student-account/);
assert.match(portalJs,/ensure_teacher_access/);assert.match(portalJs,/使用教師 Email 與密碼登入/);
assert.match(portalJs,/新增學生帳密/);assert.match(fs.readFileSync('supabase/functions/teacher-student-account/index.ts','utf8'),/create_student_account/);
assert.match(portalJs,/AI 修改建議/);assert.match(portalJs,/尚未寫入資料庫/);assert.match(fs.readFileSync('portal.css','utf8'),/teacher-plan \.portal-form textarea/);
const teacherAccountFunction=fs.readFileSync('supabase/functions/teacher-student-account/index.ts','utf8');assert.match(teacherAccountFunction,/ai_plan_suggestion/);assert.match(teacherAccountFunction,/OPENAI_API_KEY/);assert.match(teacherAccountFunction,/teacher_plan_suggestion/);
assert.match(portalJs,/教師個別回饋|一般教師留言/);
assert.match(portalJs,/chooseResearch/);
assert.match(portalJs,/research_projects/);
assert.match(portalJs,/查看此主題的心得與回饋/);
assert.match(portalJs,/以下只顯示這個主題的心得、教師回饋與研究紀錄/);
assert.match(portalJs,/back-student/);
assert.match(fs.readFileSync('index.html','utf8'),/開始新研究歷程/);
assert.match(fs.readFileSync('index.html','utf8'),/data-go="projects"[^>]*>📚 主題列表/);
assert.match(fs.readFileSync('index.html','utf8'),/data-action="logout"[^>]*>登出/);
assert.match(fs.readFileSync('index.html','utf8'),/logged-out-only/);
assert.match(fs.readFileSync('app.js','utf8'),/projects:projectList/);
assert.match(fs.readFileSync('app.js','utf8'),/目前保存 \$\{projects.length\}／5 個研究主題/);
assert.match(fs.readFileSync('index.html','utf8'),/supabase-js/);assert.match(fs.readFileSync('app.js','utf8'),/restoreSignedInUser/);
assert.match(fs.readFileSync('backend.js','utf8'),/createProject/);
assert.match(fs.readFileSync('backend.js','utf8'),/deleteProject/);
assert.match(fs.readFileSync('backend.js','utf8'),/authClient\.auth\.signOut/);
assert.match(fs.readFileSync('app.js','utf8'),/下載 PDF/);
assert.match(fs.readFileSync('app.js','utf8'),/未滿 5 個前不能刪除/);
const reflectionMigration=fs.readFileSync('supabase/migrations/202608090001_reflection_history.sql','utf8');
assert.match(reflectionMigration,/reflection_added/);
const multiResearchMigration=fs.readFileSync('supabase/migrations/202608090002_multi_research_history.sql','utf8');
for(const required of ['research_projects','login_email','research_id','原有研究歷程'])assert.ok(multiResearchMigration.includes(required),`多研究歷程 migration 缺少 ${required}`);
assert.match(studentApi,/\(count\|\|0\)>=5/);assert.match(studentApi,/\(count\|\|0\)<5/);assert.match(studentApi,/action==='delete_project'/);
const experimentMigration=fs.readFileSync('supabase/migrations/202607200001_experiment_records.sql','utf8');
const discussionMigration=fs.readFileSync('supabase/migrations/202607200002_research_discussions.sql','utf8');
const experimentReview=fs.readFileSync('supabase/functions/experiment-review/index.ts','utf8');
for(const required of ['experiment_records','experiment_uploaded','experiment_reviewed','8388608'])assert.ok(experimentMigration.includes(required),`實驗 migration 缺少 ${required}`);
assert.match(discussionMigration,/record_kind/);assert.match(discussionMigration,/discussion/);
for(const required of ['研究問題','重複次數','明顯不合理','不可捏造'])assert.ok(experimentReview.includes(required),`實驗分析缺少 ${required}`);
const adminMigration=fs.readFileSync('supabase/migrations/202608110001_admin_and_teacher_access.sql','utf8');
for(const required of ['teacher_profiles','teacher_google_login','administrators','admin_sessions','ensure_teacher_access','is_active_teacher'])assert.ok(adminMigration.includes(required),`管理者 migration 缺少 ${required}`);
const adminApi=fs.readFileSync('supabase/functions/admin-api/index.ts','utf8');
for(const required of ['change_password','create_teacher','create_class','create_student','set_google_login','student_detail','thought_events','research_plans','experiment_records','reset_teacher_password','reset_student_password','updateUserById','PASSWORD_CHANGE_REQUIRED'])assert.ok(adminApi.includes(required),`管理者 API 缺少 ${required}`);
assert.ok(!adminApi.includes('classes!inner(id,name,teacher_profiles!inner'),'管理者學生詳情不可使用不存在的班級→教師設定檔外鍵');
assert.match(fs.readFileSync('admin.html','utf8'),/總管理者/);assert.match(fs.readFileSync('admin.js','utf8'),/所有教師、班級與學生/);
for(const required of ['查看學習歷程與心得','學生心得歷程','四個主類別的思考證據鏈','完整原始事件時間軸','總管理者唯讀檢視','更改教師密碼','更改學生密碼','experimentSection(data.experimentRecords'])assert.ok(fs.readFileSync('admin.js','utf8').includes(required),`管理頁缺少 ${required}`);
assert.match(fs.readFileSync('admin.html','utf8'),/admin\.js\?v=/);
console.log('✓ 後端連線入口、RLS、保存期限、排程刪除、PIN雜湊與登入限速皆存在');
