import {JSDOM} from 'jsdom';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync('index.html','utf8').replace('<script src="app.js"></script>','');
const dom=new JSDOM(html,{url:'https://example.test/',runScripts:'dangerously'});
dom.window.confirm=()=>true;
dom.window.scrollTo=()=>{};
dom.window.eval(fs.readFileSync('app.js','utf8'));
const {document}=dom.window;
const click=selector=>{const el=document.querySelector(selector);assert.ok(el,`找不到 ${selector}`);el.click()};
click('[data-go="division"]');
assert.match(document.querySelector('#app').textContent,/想參加哪一個科別/);
click('[data-division="biology"]');
click('[data-next="profile"]');
document.querySelector('#grade').value='5';
document.querySelector('#weeks').value='8';
document.querySelector('#budget').value='10,000 元';
click('[data-interest="植物"]');
click('[data-profile]');
assert.match(document.querySelector('#app').textContent,/同時符合科別與興趣的題目/);
click('[data-topic="b1"]');
click('[data-next="plan"]');
assert.match(document.querySelector('#app').textContent,/光的方向與豆苗彎曲/);
click('[data-action="teacher"]');
assert.match(document.querySelector('#app').textContent,/教師確認清單/);
assert.equal(JSON.parse(dom.window.localStorage.getItem('scienceFairCoachV1')).topicId,'b1');
assert.equal(JSON.parse(dom.window.localStorage.getItem('scienceFairCoachV1')).budget,'10,000 元');
click('[data-action="reset"]');
click('[data-go="division"]');
click('[data-division="math"]');
click('[data-next="profile"]');
click('[data-interest="植物"]');
click('[data-profile]');
const recommendation=document.querySelector('#app').textContent;
assert.match(recommendation,/校園植物葉序與遮蔽率的數學模型/);
assert.match(recommendation,/生物科更合適/);
assert.match(recommendation,/向日葵的生長密碼/);
console.log('✓ 選題流程、教師檢視、本機儲存、科別＋興趣交集與歷屆作品皆通過');

const portalHtml=fs.readFileSync('portal.html','utf8').replace(/<script[^>]*><\/script>/g,'');
const portalDom=new JSDOM(portalHtml,{url:'https://example.test/portal.html',runScripts:'dangerously'});
portalDom.window.eval(fs.readFileSync('config.js','utf8'));
portalDom.window.eval(fs.readFileSync('portal.js','utf8'));
assert.match(portalDom.window.document.querySelector('#portal').textContent,/後端尚未連線/);

const migration=fs.readFileSync('supabase/migrations/202607180001_initial.sql','utf8');
for(const required of ['enable row level security','365 days','395 days','purge_expired_students','pg_cron','teachers view thought histories'])assert.ok(migration.includes(required),`migration缺少 ${required}`);
const studentApi=fs.readFileSync('supabase/functions/student-api/index.ts','utf8');
assert.match(studentApi,/PBKDF2/);assert.match(studentApi,/嘗試次數過多/);
console.log('✓ 未連線入口、RLS、保存期限、排程刪除、PIN雜湊與登入限速皆存在');
