import {JSDOM} from 'jsdom';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync('index.html','utf8').replace('<script src="app.js"></script>','');
const dom=new JSDOM(html,{url:'https://example.test/',runScripts:'dangerously'});
dom.window.confirm=()=>true;
dom.window.scrollTo=()=>{};
dom.window.eval(fs.readFileSync('app.js','utf8'));
const {document}=dom.window;
const click=selector=>{const el=document.querySelector(selector);assert.ok(el,`找不到 ${selector}`);el.click()};
click('[data-go="division"]');
assert.match(document.querySelector('#app').textContent,/想參加哪一個科別/);
click('[data-division="biology"]');
click('[data-next="profile"]');
document.querySelector('#grade').value='5';
document.querySelector('#weeks').value='8';
document.querySelector('#budget').value='10,000 元';
click('[data-interest="植物"]');
click('[data-profile]');
assert.match(document.querySelector('#app').textContent,/第 1 輪/);
assert.doesNotMatch(document.querySelector('#app').textContent,/經人工整理的備援題目/);
document.querySelector('#guide-answer').value='我喜歡每天觀察窗邊豆苗朝著陽光彎曲的樣子';
click('[data-guide-submit]');await new Promise(resolve=>setTimeout(resolve,0));
document.querySelector('#guide-answer').value='我想知道光從不同方向照過來是不是會讓彎曲角度不同';
click('[data-guide-submit]');await new Promise(resolve=>setTimeout(resolve,0));
assert.match(document.querySelector('#app').textContent,/完成對談並查看推薦/);
click('[data-go="profile"]');
assert.equal(document.querySelector('#grade').value,'5');
assert.equal(document.querySelector('#weeks').value,'8');
assert.equal(document.querySelector('#budget').value,'10,000 元');
assert.match(document.querySelector('#app').textContent,/上一步：選擇科別/);
click('[data-profile]');
assert.match(document.querySelector('#app').textContent,/我喜歡每天觀察窗邊豆苗/);
assert.doesNotMatch(document.querySelector('#app').textContent,/經人工整理的備援題目/);
click('[data-guide-finish]');
assert.match(document.querySelector('#app').textContent,/同時符合科別、興趣與你的想法/);
click('[data-topic="b1"]');
click('[data-next="plan"]');
assert.match(document.querySelector('#app').textContent,/光的方向與豆苗彎曲/);
assert.match(document.querySelector('#app').textContent,/實驗紀錄與討論/);
click('[data-go="experiment"]');
document.querySelector('#record-method').value='設三組不同光源方向，每組重複測量五次';
document.querySelector('#record-result').value='平均彎曲角度分別是 10、25、40 度';
click('[data-record-submit]');await new Promise(resolve=>setTimeout(resolve,0));
assert.match(document.querySelector('#app').textContent,/教練回饋/);
click('[data-go="plan"]');
click('[data-action="teacher"]');
assert.match(document.querySelector('#app').textContent,/教師確認清單/);
assert.equal(JSON.parse(dom.window.localStorage.getItem('scienceFairCoachV1')).topicId,'b1');
assert.equal(JSON.parse(dom.window.localStorage.getItem('scienceFairCoachV1')).budget,'10,000 元');
click('[data-action="reset"]');
click('[data-go="division"]');
click('[data-division="math"]');
click('[data-next="profile"]');
click('[data-interest="植物"]');
click('[data-profile]');
document.querySelector('#guide-answer').value='我喜歡觀察校園裡不同植物葉子的排列方式';
click('[data-guide-submit]');await new Promise(resolve=>setTimeout(resolve,0));
document.querySelector('#guide-answer').value='我想知道葉片角度是否會影響互相遮住的面積';
click('[data-guide-submit]');await new Promise(resolve=>setTimeout(resolve,0));
click('[data-guide-finish]');
const recommendation=document.querySelector('#app').textContent;
assert.match(recommendation,/校園植物葉序與遮蔽率的數學模型/);
assert.match(recommendation,/生物科更合適/);
assert.match(recommendation,/向日葵的生長密碼/);
console.log('✓ 選題流程、教師檢視、本機儲存、科別＋興趣交集與歷屆作品皆通過');

const portalHtml=fs.readFileSync('portal.html','utf8').replace(/<script[^>]*><\/script>/g,'');
const portalDom=new JSDOM(portalHtml,{url:'https://example.test/portal.html',runScripts:'dangerously'});
portalDom.window.eval(fs.readFileSync('config.js','utf8'));
portalDom.window.supabase={createClient:()=>({auth:{
  getSession:async()=>({data:{session:null}}),
  onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})
}})};
portalDom.window.eval(fs.readFileSync('portal.js','utf8'));
await new Promise(resolve=>setTimeout(resolve,0));
assert.doesNotMatch(portalDom.window.document.querySelector('#portal').textContent,/後端尚未連線/);
assert.equal(portalDom.window.document.querySelector('#google').disabled,false);

const migration=fs.readFileSync('supabase/migrations/202607180001_initial.sql','utf8');
for(const required of ['enable row level security','365 days','395 days','purge_expired_students','pg_cron','teachers view thought histories'])assert.ok(migration.includes(required),`migration缺少 ${required}`);
const studentApi=fs.readFileSync('supabase/functions/student-api/index.ts','utf8');
assert.match(studentApi,/PBKDF2/);assert.match(studentApi,/嘗試次數過多/);
const experimentMigration=fs.readFileSync('supabase/migrations/202607200001_experiment_records.sql','utf8');
const experimentReview=fs.readFileSync('supabase/functions/experiment-review/index.ts','utf8');
for(const required of ['experiment_records','experiment_uploaded','experiment_reviewed','8388608'])assert.ok(experimentMigration.includes(required),`實驗 migration 缺少 ${required}`);
for(const required of ['研究問題','重複次數','明顯不合理','不可捏造'])assert.ok(experimentReview.includes(required),`實驗分析缺少 ${required}`);
console.log('✓ 後端連線入口、RLS、保存期限、排程刪除、PIN雜湊與登入限速皆存在');
