import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
import {corsHeaders,json} from '../_shared/cors.ts';
const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);const enc=new TextEncoder();
async function sha(value:string){const bytes=await crypto.subtle.digest('SHA-256',enc.encode(value));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function student(req:Request){const token=req.headers.get('x-student-token');if(!token)return null;const {data}=await db.from('student_sessions').select('student_id,expires_at,students(*)').eq('token_hash',await sha(token)).gt('expires_at',new Date().toISOString()).maybeSingle();return data?.students||null}
const schema={type:'object',additionalProperties:false,required:['stage','questions','topics','sources'],properties:{stage:{type:'string',enum:['questions','topics']},questions:{type:'array',maxItems:5,items:{type:'string'}},sources:{type:'array',items:{type:'object',additionalProperties:false,required:['title','url','kind','published_date'],properties:{title:{type:'string'},url:{type:'string'},kind:{type:'string'},published_date:{type:'string'}}}},topics:{type:'array',maxItems:4,items:{type:'object',additionalProperties:false,required:['title','division','fit','current_issue','research_question','novelty','variables','feasibility','safety','prior_works'],properties:{title:{type:'string'},division:{type:'string'},fit:{type:'string'},current_issue:{type:'string'},research_question:{type:'string'},novelty:{type:'string'},variables:{type:'string'},feasibility:{type:'string'},safety:{type:'string'},prior_works:{type:'array',items:{type:'object',additionalProperties:false,required:['title','url','relationship'],properties:{title:{type:'string'},url:{type:'string'},relationship:{type:'string'}}}}}}}}};
Deno.serve(async req=>{
  if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});
  try{
    const s:any=await student(req);if(!s)return json({error:'學生登入已失效'},401);if(new Date(s.active_until)<=new Date())return json({error:'紀錄已進入唯讀期'},423);
    const since=new Date();since.setHours(0,0,0,0);const {count}=await db.from('ai_usage').select('*',{count:'exact',head:true}).eq('student_id',s.id).gte('used_at',since.toISOString());if((count||0)>=5)return json({error:'今天的動態題目次數已用完，仍可使用內建題庫'},429);
    const body=await req.json();if(JSON.stringify(body).length>20000)return json({error:'問答內容過長'},413);if(!Array.isArray(body.profile?.guidance)||body.profile.guidance.length<2)return json({error:'請先完成至少兩輪想法對談'},400);const apiKey=Deno.env.get('OPENAI_API_KEY');if(!apiKey)return json({error:'AI服務尚未啟用'},503);const model=Deno.env.get('OPENAI_MODEL')||'gpt-5.6';
    const prompt=`你是臺灣國小科展選題教練。學生資料：${JSON.stringify(body.profile||{})}。已完成問答：${JSON.stringify(body.answers||[])}。
學生已先完成至少兩輪深入對談，不要再提問，stage必須是topics且questions留空。搜尋近兩年（以今天往前730天）可信的時事或科學議題，並優先搜尋 twsf.ntsec.gov.tw 科教館歷屆全國科展作品。提出3至4題，不可只把熱門詞放進標題。
每題要說明科別關聯、興趣關聯、近期議題及日期、可量測研究問題、與前人作品差異、創新方向、變因、時間材料可行性與安全倫理。找不到可核對的科教館作品時，prior_works留空，不得虛構。所有URL必須是實際搜尋所得。`;
    const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Authorization':`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model,reasoning:{effort:'low'},tools:[{type:'web_search',search_context_size:'medium'}],include:['web_search_call.action.sources'],input:[{role:'developer',content:'只輸出符合JSON Schema的繁體中文內容。資料來源不確定就明說，不可編造作品、作者、名次、日期或URL。'},{role:'user',content:prompt}],text:{format:{type:'json_schema',name:'science_fair_recommendation',strict:true,schema}}})});
    const result=await response.json();if(!response.ok){console.error(result);return json({error:'AI服務暫時無法產生題目'},502)}const outputText=result.output_text||result.output?.flatMap((x:any)=>x.content||[]).find((x:any)=>x.type==='output_text')?.text;if(!outputText)throw new Error('missing model output');const output=JSON.parse(outputText);await db.from('ai_usage').insert({student_id:s.id,model,request_id:result.id});await db.from('thought_events').insert({student_id:s.id,event_type:output.stage==='questions'?'question_shown':'topics_recommended',content:{mode:'dynamic',result:output},source:'system'});return json({result:output,requestId:result.id});
  }catch(error){console.error(error);return json({error:'動態題目處理失敗'},500)}
});
