PRAGMA foreign_keys = ON;

CREATE TABLE teachers(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,password_hash TEXT,display_name TEXT,active INTEGER NOT NULL DEFAULT 1,provider TEXT NOT NULL DEFAULT 'password',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE teacher_sessions(id TEXT PRIMARY KEY,teacher_id TEXT NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE classes(id TEXT PRIMARY KEY,teacher_id TEXT NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,name TEXT NOT NULL CHECK(length(name) BETWEEN 1 AND 80),join_code TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE students(id TEXT PRIMARY KEY,class_id TEXT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,student_code TEXT NOT NULL,login_email TEXT,display_label TEXT,password_hash TEXT NOT NULL,profile TEXT NOT NULL DEFAULT '{}',selected_topic TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,active_until TEXT NOT NULL,delete_after TEXT NOT NULL,UNIQUE(class_id,student_code));
CREATE UNIQUE INDEX students_active_email ON students(lower(login_email)) WHERE login_email IS NOT NULL;
CREATE TABLE student_sessions(id TEXT PRIMARY KEY,student_id TEXT NOT NULL REFERENCES students(id) ON DELETE CASCADE,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE login_attempts(id INTEGER PRIMARY KEY AUTOINCREMENT,attempt_key TEXT NOT NULL,attempted_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX login_attempts_key_time ON login_attempts(attempt_key,attempted_at);
CREATE TABLE research_projects(id TEXT PRIMARY KEY,student_id TEXT NOT NULL REFERENCES students(id) ON DELETE CASCADE,title TEXT NOT NULL DEFAULT '新研究歷程',status TEXT NOT NULL DEFAULT 'active',profile TEXT NOT NULL DEFAULT '{}',selected_topic TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX research_projects_student_time ON research_projects(student_id,created_at DESC);
CREATE TABLE thought_events(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id TEXT NOT NULL REFERENCES students(id) ON DELETE CASCADE,research_id TEXT NOT NULL REFERENCES research_projects(id) ON DELETE CASCADE,event_type TEXT NOT NULL,content TEXT NOT NULL DEFAULT '{}',source TEXT NOT NULL DEFAULT 'student',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX thought_events_research_time ON thought_events(research_id,created_at);
CREATE TABLE research_plans(research_id TEXT PRIMARY KEY REFERENCES research_projects(id) ON DELETE CASCADE,student_id TEXT NOT NULL REFERENCES students(id) ON DELETE CASCADE,system_plan TEXT NOT NULL,current_plan TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE plan_suggestions(id TEXT PRIMARY KEY,research_id TEXT NOT NULL REFERENCES research_projects(id) ON DELETE CASCADE,student_id TEXT NOT NULL REFERENCES students(id) ON DELETE CASCADE,teacher_id TEXT NOT NULL REFERENCES teachers(id),comment TEXT NOT NULL,proposed_plan TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,decided_at TEXT);
CREATE TABLE experiment_records(id TEXT PRIMARY KEY,student_id TEXT NOT NULL REFERENCES students(id) ON DELETE CASCADE,research_id TEXT NOT NULL REFERENCES research_projects(id) ON DELETE CASCADE,subtopic_id TEXT,record_kind TEXT NOT NULL DEFAULT 'experiment',topic_snapshot TEXT,method TEXT NOT NULL,result TEXT NOT NULL,file_name TEXT,file_key TEXT,mime_type TEXT,ai_review TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX experiments_research_time ON experiment_records(research_id,created_at);
CREATE TABLE ai_usage(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id TEXT NOT NULL REFERENCES students(id) ON DELETE CASCADE,used_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,model TEXT NOT NULL,request_id TEXT);
CREATE TABLE administrators(id TEXT PRIMARY KEY,username TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,must_change_password INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE admin_sessions(id TEXT PRIMARY KEY,administrator_id TEXT NOT NULL REFERENCES administrators(id) ON DELETE CASCADE,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE app_settings(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO app_settings(key,value) VALUES('teacher_google_login','false');
CREATE TABLE schema_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
INSERT INTO schema_meta(key,value) VALUES('schema_version','1'),('source','cloudflare-d1');
